# Generated by Django 6.0.6 on 2026-06-05 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(blank=True, max_length=255)),
                ('cover_image', models.URLField(blank=True)),
                ('language', models.CharField(blank=True, max_length=10)),
                ('external_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('cached_at', models.DateTimeField(blank=True, null=True)),
                ('cache_ttl', models.PositiveIntegerField(default=3600)),
                ('tags', models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('cover_image', models.URLField(blank=True)),
                ('book_count', models.PositiveIntegerField(default=0)),
                ('selection_author', models.CharField(blank=True, max_length=255)),
                ('external_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('cached_at', models.DateTimeField(blank=True, null=True)),
                ('cache_ttl', models.PositiveIntegerField(default=3600)),
                ('tags', models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Edition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(db_index=True, max_length=13)),
                ('format', models.CharField(blank=True, max_length=50)),
                ('publisher', models.CharField(blank=True, max_length=255)),
                ('published_date', models.CharField(blank=True, max_length=20)),
                ('cached_at', models.DateTimeField(blank=True, null=True)),
                ('cache_ttl', models.PositiveIntegerField(default=3600)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editions', to='books.book')),
            ],
        ),
    ]
