# Generated by Django 6.0.6 on 2026-06-30 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_collectionbook'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cached_at', models.DateTimeField(auto_now=True)),
                ('cache_ttl', models.PositiveIntegerField()),
                ('source', models.CharField(db_index=True, max_length=50)),
                ('slug', models.CharField(db_index=True, max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('filter_config', models.JSONField(default=dict)),
            ],
        ),
        migrations.AlterField(
            model_name='book',
            name='external_id',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='collection',
            name='external_id',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.CreateModel(
            name='FacetCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facet_collections', to='books.collection')),
                ('facet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facet_collections', to='books.facet')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('facet', 'collection')},
            },
        ),
        migrations.AddField(
            model_name='facet',
            name='collections',
            field=models.ManyToManyField(blank=True, related_name='facets', through='books.FacetCollection', to='books.collection'),
        ),
        migrations.AlterUniqueTogether(
            name='facet',
            unique_together={('slug', 'source')},
        ),
    ]
