# Generated by Django 6.0.6 on 2026-06-30 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_facet'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='filter_config',
            field=models.JSONField(default=dict),
        ),
    ]
