# Generated by Django 6.0.6 on 2026-07-01 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_collection_filter_config'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='language',
        ),
        migrations.AddField(
            model_name='edition',
            name='language',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
