# Generated by Django 6.0.6 on 2026-06-06 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('community', models.CharField(max_length=100)),
                ('base_url', models.URLField()),
                ('backend', models.CharField(choices=[('odilo', 'Odilo JSON'), ('web', 'Web scraping')], default='odilo', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Copy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cached_at', models.DateTimeField(auto_now=True)),
                ('cache_ttl', models.PositiveIntegerField()),
                ('source', models.CharField(db_index=True, max_length=50)),
                ('isbn', models.CharField(db_index=True, max_length=13)),
                ('available', models.BooleanField(null=True)),
                ('borrow_url', models.URLField(blank=True)),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copies', to='availability.catalog')),
            ],
            options={
                'verbose_name_plural': 'copies',
                'unique_together': {('isbn', 'catalog', 'source')},
            },
        ),
    ]
