# Generated by Django 6.0.6 on 2026-06-14 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('availability', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='odilo_client_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='catalog',
            name='odilo_client_secret',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='backend',
            field=models.CharField(choices=[('odilo', 'Odilo JSON'), ('web', 'Web scraping')], default='web', max_length=20),
        ),
    ]
