# Generated by Django 6.0.6 on 2026-07-06 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('availability', '0002_catalog_odilo_client_id_catalog_odilo_client_secret_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='copy',
            name='author',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='copy',
            name='format',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='copy',
            name='language',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='copy',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
