# Generated by Django 6.0.6 on 2026-07-06 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('availability', '0003_copy_author_copy_format_copy_language_copy_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='copy',
            name='cover_image',
            field=models.URLField(blank=True, default=''),
        ),
    ]
